<a href="https://colab.research.google.com/github/MNairobi/First/blob/main/SubscribersData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import pandas as pd

Saving SubscribersData.csv to SubscribersData.csv

In [ ]:

data = pd.read_csv('SubscribersData.csv')
head = data.head(10)
print(head)

   SubscriberIdentityNumber  Phone Number Subscriber Name        SSN  \
0           345278656547333    1654788999            Mike  214448881
1           345278666547334    1888777222            John  214448882
2           345278676547335    1122765445           James  214448883
3           345278686547336            10          Robert  214448884
4           345278696547337    1590741891          Thomas  214448885
5           345278706547338            20         Charles  214448886
6           345278716547339    1058718337             Sam  214448887
7           345278726547340    1292706560          Antony  214448888
8           345278736547341    1526694783             Raj  214448889
9           345278746547342    1526694784           Brian  214448890

   Subscriber Age    State  Zip Code SubscribedFromDate Internet Service  \
0              25  Arizona     85005          1/12/2018           Active
1              15  Florida     33130         12/12/2018           Active
2              45  Newyork     10005          5/25/2018           Active
3              62  Newyork     10006          11/5/2017         InActive
4              15  Newyork     10007          4/18/2017           Active
5              33  Newyork     10008          9/29/2019           Active
6              22  Newyork     10009          3/12/2016           Active
7              78  Newyork     10010          8/24/2015           Active
8              55  Newyork     10011           2/4/2019           Active
9              44  Newyork     10012           2/5/2019           Active

  SMS Service Churn Status
0      Active       Active
1      Active       Active
2      Active       Active
3         NaN       Active
4      Active          NaN
5      Active       Active
6      Active       Active
7      Active       Active
8      Active          NaN
9      Active       Active

In [ ]:
#i want to know the structure of the subscribers data,columns,memory usage,data type,the number of rows
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SubscriberIdentityNumber  505 non-null    int64
 1   Phone Number              505 non-null    int64
 2   Subscriber Name           505 non-null    object
 3   SSN                       505 non-null    int64
 4   Subscriber Age            505 non-null    int64
 5   State                     505 non-null    object
 6   Zip Code                  505 non-null    int64
 7   SubscribedFromDate        505 non-null    object
 8   Internet Service          505 non-null    object
 9   SMS Service               501 non-null    object
 10  Churn Status              499 non-null    object
dtypes: int64(5), object(6)
memory usage: 43.5+ KB

In [ ]:
#i want to know the number of rows and columns of this data
data.shape

(505, 11)

In [ ]:
#Using the relevant functions determine if any column has null values
data.isnull().sum()

SubscriberIdentityNumber    0
Phone Number                0
Subscriber Name             0
SSN                         0
Subscriber Age              0
State                       0
Zip Code                    0
SubscribedFromDate          0
Internet Service            0
SMS Service                 4
Churn Status                6
dtype: int64

In [ ]:
#Compute the measures of central tendency in the numeric columns of the dataset
data.describe()

,SubscriberIdentityNumber,Phone Number,SSN,Subscriber Age,Zip Code
count,5.050000e+02,5.050000e+02,5.050000e+02,505.000000,505.000000
mean,3.452812e+14,1.513510e+09,2.144491e+08,38.572277,33571.891089
std,1.458411e+09,1.396134e+08,1.458410e+02,14.192946,17933.348377
min,3.452787e+14,1.000000e+01,2.144489e+08,15.000000,7039.000000
25%,3.452799e+14,1.526695e+09,2.144490e+08,30.000000,10017.000000
50%,3.452812e+14,1.526695e+09,2.144491e+08,36.000000,44115.000000
75%,3.452824e+14,1.526695e+09,2.144493e+08,44.000000,44140.000000
max,3.452836e+14,1.888777e+09,2.144494e+08,78.000000,85005.000000

In [ ]:
# Select only numeric columns for calculating the mean
numeric_data = data.select_dtypes(include=['number'])
mean = numeric_data.mean()
print(mean)

SubscriberIdentityNumber    3.452812e+14
Phone Number                1.513510e+09
SSN                         2.144491e+08
Subscriber Age              3.857228e+01
Zip Code                    3.357189e+04
dtype: float64

In [ ]:
# Fill NaN values in the original DataFrame using the calculated means
data.fillna(mean, inplace=True)
data.isnull().sum()

SubscriberIdentityNumber    0
Phone Number                0
Subscriber Name             0
SSN                         0
Subscriber Age              0
State                       0
Zip Code                    0
SubscribedFromDate          0
Internet Service            0
SMS Service                 4
Churn Status                6
dtype: int64

In [ ]:
#fill  null valuea dor the non numerical colmns
non_numerical_cols = data.select_dtypes(exclude=['number']).columns
data[non_numerical_cols] = data[non_numerical_cols].fillna(data[non_numerical_cols].mode().iloc[0])

data.isnull().sum()
# categorical_cols = data.select_dtypes(include=['object']).columns

# # Fill NaN values with mode for each categorical column
# for col in categorical_cols:
#     data[col].fillna(data[col].mode()[0], inplace=True)

# data.isnull().sum()

SubscriberIdentityNumber    0
Phone Number                0
Subscriber Name             0
SSN                         0
Subscriber Age              0
State                       0
Zip Code                    0
SubscribedFromDate          0
Internet Service            0
SMS Service                 0
Churn Status                0
dtype: int64

In [ ]:
#Determine any outliers in your dataset either through visualization or using the numpy
#Z-score
import numpy as np
from scipy import stats
# Select only numeric columns for calculating the z-score
numeric_data = data.select_dtypes(include=['number'])

z_scores = np.abs(stats.zscore(numeric_data))
outliers = np.where(z_scores > 3)
print(outliers)
data.shape

(array([ 3,  5,  6, 13, 16]), array([1, 1, 1, 1, 1]))

In [ ]:
#Drop the rows with outliers
# data = data[(z_scores < 3).all(axis=1)]
# data.shape

import numpy as np
from scipy import stats

# Select only numeric columns for calculating the z-score
numeric_data = data.select_dtypes(include=['number'])

z_scores = np.abs(stats.zscore(numeric_data))
outlier_rows = np.where(z_scores > 3)[0]

# Drop the rows with outliers
data = data.drop(outlier_rows)
data.shape

(500, 11)

In [27]:
#Check for duplicates using an ideal method/function and remove the duplicates if any.
data.duplicated().sum()

5

In [28]:
#remove duplicates
data = data.drop_duplicates()
data.duplicated().sum()

0

In [29]:
#. Print/check the final shape of your dataset after performing this pre-processing
# Using pandas .to_csv ( ) save the pre-processed data sets
data.shape
data.to_csv('preprocessed_data.csv', index=False)